### ISSUE TITLE
Tmux Plugin is too slow 

### ISSUE THREAD

**Issue by MushiTheMoshi** [fcsonline/tmux-thumbs#88] opened 2021-06-15 15:11 UTC
Hi there, awesome plugin, very productive one. Thanks for the job done here very appreciated. 
I found that tmux plugin is really slow in compare with the standalone thumb, it takes up to 10 secs to find all occurs, I was wondering how can I troubleshoot this, just to see if I can somehow improve it.

**Comment by Morantron** [comment] 2021-06-16 06:43
I'm facing the same issue.

**Comment by fcsonline** [comment] 2021-06-16 06:47
It usually works for me in milliseconds. Can you give us a bit of context?

**Comment by MushiTheMoshi** [comment] 2021-06-16 17:14
Hi there, well , when the screen is full of occurrences is happening, see below:

![byzanz_2021-06-16_111103](https://user-images.githubusercontent.com/13651419/122263747-0340eb80-ce94-11eb-9dc6-ebf1a0899ca3.gif)

**Comment by fcsonline** [comment] 2021-06-17 07:06
Do you have some custom regex that is matching every word or something like this? It is really weird this amount of matches.

**Comment by MushiTheMoshi** [comment] 2021-06-30 13:27
I found the reason, it was related to the tmux alerts, if activated those collide and you get the idea of incompleteness since the plugin wait until the alert is gone, when turned off everything works just fine

**Comment by fcsonline** [comment] 2021-06-30 14:15
Not sure to fully get it, but if it works, that's ok. :ok_hand:

**Comment by fcsonline** [comment] 2021-06-30 14:16
Closing issue.

**Closed by fcsonline** 2021-06-30 14:16 UTC

**Comment by jetm** [comment] 2021-06-30 15:14
@MushiTheMoshi I having a similar issue. What did you change in your tmux.conf file?

**Comment by julioOlea** [comment] 2021-06-30 15:44
I edited as below:
```
set -g visual-activity off
set -g visual-bell off
set -g visual-silence on
```

**Comment by MushiTheMoshi** [comment] 2021-06-30 15:45
I edited as below:

set -g visual-activity off
set -g visual-bell off
set -g visual-silence on

**Comment by jetm** [comment] 2021-06-30 16:03
@MushiTheMoshi Thank you! That solved my issue too.

**Comment by fcsonline** [comment] 2021-06-30 18:31
But just to understand, what is the cause to end up in this situation? I never faced this. I can understand the relationship between showing hints and visual-bell, visual-activity, etc.

**Comment by MushiTheMoshi** [comment] 2021-06-30 20:59
my understanding is that when you issue a command inside a tmux session, it's registered and tmux alerts about it, that behaviour is like colliding with the plugin execution, I notice by hitting enter while waiting for the hinting links. That's when I come with the ideo to turn off the alerts, bells etc.

**Comment by JoyceBabu** [comment] 2021-08-17 07:17
Thank you @MushiTheMoshi. I first tried tmux-thumbs a few months back and stopped using it due to the very slow response. Your solution worked for me too.

**Comment by fcsonline** [comment] 2021-08-17 08:31
I just added a bit of documentation about this: https://github.com/fcsonline/tmux-thumbs/blob/master/README.md#troubleshooting

Thank you all for handling this.
