### ISSUE TITLE
Plugin manager?

### ISSUE THREAD

**Issue by ywpkwon** [fcsonline/tmux-thumbs#26] opened 2020-02-21 22:37 UTC
Is there a way to install tmux-thumbs simply through a tmux plugin manager (tpm)?
E.g., `set -g @plugin 'Morantron/tmux-thumbs'`?

**Comment by fcsonline** [comment] 2020-03-15 12:11
Hi, I just added information how to configure tmux-thumbs with TPM.

Let me know if it works for you.

**Comment by ywpkwon** [comment] 2020-03-26 11:00
Hi, thanks for your support. I tried. I think the installation itself works. 
However, unfortunately at this moment, it seems a bit more unstable than `tmux-fingers`.

[error cases]
1. My window is split vertically. In the lower panel, I tried to hit thumb-key. It suddenly shows links in earlier screen (screen at the beginning which is in up scroll). When I tried figner-key, it shows links in the current visible screen.  
2. When I hit a link key, `tmux-fingers` copies it into my system clipboard correctly, but `tmux-thumbs` doesn't copy it into my system clipboard. (terminal's paste doesn't give the text).

I don't know if this is just my case. I think `tmux-thumbs` is really a good project since it seems to provide many features. I hope this project keep being awesome!

**Comment by fcsonline** [comment] 2020-04-05 10:44
Thanks to report this. I'm not able to reproduce the first error. I tried to play with thumbs with many layouts and panes but I can't hit it. If you have time, could you try to reproduce it again? I remember a similar bug in older versions. Check out master. :pray: 

About the second one, I'll investigate if I can do something. :ok_hand:

**Comment by fcsonline** [comment] 2020-05-03 13:44
I'm closing this issue because the original problem with TPM was solved. If you can reproduce those other issues, feel free to open new issues with the details.

**Closed by fcsonline** 2020-05-03 13:44 UTC
