### ISSUE TITLE
BUG: non full window pane gets scrolled up

### ISSUE THREAD

**Issue by nkh** [fcsonline/tmux-thumbs#64] opened 2020-09-16 07:59 UTC
hitting prefix + space in a  pane (in a windows containing multiple panes), displays the whole buffer rather than only the visible contents of the pane. which means that one can't select what one sees but something one saw a while ago.

**Comment by ianjsikes** [comment] 2020-11-12 16:13
I'm glad I'm not alone. [Here is a video demonstrating the same thing](https://streamable.com/wu3max). When I enter thumbs mode, you can see it jumps up some amount. When I switch to a zoomed pane, it doesn't.

It appears that the amount that it jumps up is related to the size of the split. If I resize the pane so it is larger than the other split pane, the amount jumped up is smaller.

My environment:
- MacOS 10.15.7
- fish shell 3.1.2
- iTerm2 3.3.12
- tmux 3.1c

[Here are my fish and tmux config files.](https://gist.github.com/ianjsikes/6af6a59a5f92a84ee31c480a9bf504a8)

**Comment by ianjsikes** [comment] 2020-11-17 15:35
This looks like it may be a related issue that was resolved on tmux-fingers: https://github.com/Morantron/tmux-fingers/commit/69a69326fb7fe3f6d72beacc3c646203061a3a8c

I really don't know enough about the terminal to understand the issue, but I may clone the project and start poking at things this weekend and see what I can learn.

**Comment by fcsonline** [comment] 2020-11-27 16:12
Yep, I was able to reproduce the problem. I'll try to solve it asap.

**Comment by fcsonline** [comment] 2020-12-01 17:38
I think I fixed the issue. Can you check the latest code in master?

**Comment by ianjsikes** [comment] 2020-12-01 17:46
Aww yeah!! I can confirm that it is fixed as of https://github.com/fcsonline/tmux-thumbs/commit/422eed9ecc5408ab2393a2808e85ccf6a25026db

**Comment by fcsonline** [comment] 2020-12-01 17:49
Awesome! Should I close the issue?

**Closed** 2020-12-01 17:54 UTC
Labels: bug
